[versions]
kotlin = "2.1.0"
jline = "3.28.0"
shadow = "8.3.5"

[libraries]
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
jline-console = { group = "org.jline", name = "jline-console-ui", version.ref = "jline" }

